---
name: geoip2web
pack: geoip2
description: Publish geopip2 at https://st2/GeoIP2.txt
enabled: true
trigger:
    type: geoip2.download_unzip
criteria:                              # optional
        trigger: 
          type: "exists" 
          pattern: "path" 
action:
    ref: geoip2.pandas_publish
    parameters:
        path: "{{trigger.path}}"       