---
name: geoip2web
pack: geoip2
description: Extract interested subnets from GeoIP2 db
enabled: true
trigger:
    type: geoip2.download_unzip
criteria:                              # optional
        trigger: 
          type: "exists" 
          pattern: "files" 
action:
    ref: core.sendmail
    parameters:
        subject: "GeoIP2 was updated"
        body: "{{ trigger.files }}\n\n\n"
        from: "st2@commonwealth.com"
        to: "iromaniuk@commonwealth.com"