---
name: geoip2email
pack: geoip2
description: Download, unzip GeoIP2 db and notify
enabled: false
trigger:
    type: geoip2.download_unzip
criteria:                              # optional
        trigger: 
          type: "exists" 
          pattern: "path" 
action:
    ref: core.sendmail
    parameters:
        subject: "GeoIP2 was updated"
        body: "{{ trigger.path }}\n\n\n"
        from: "st2@commonwealth.com"
        to: "iromaniuk@commonwealth.com"