---
name: geoip2web
pack: geoip2
description: Export subnets to /opt/stackstorm/static/webui/geoip2.txt
enabled: true
trigger:
    type: geoip2.download_unzip
criteria:                              # optional
        trigger: 
          type: "exists" 
          pattern: "path" 
action:
    ref: geoip2.pandas_publish
    parameters:
        path: "{{trigger.path}}"       