---
name: pandastest
pack: geoip2
description: Extract subnets into geopi2.txt file
enabled: false
trigger:
    type: geoip2.download_unzip
criteria:                              # optional
        trigger: 
          type: "exists" 
          pattern: "path" 
action:
    ref: geoip2.pandas_publish
    parameters:
        date: "{{trigger.path}}"
        