---
name: notifyzip
pack: geoip2
description: Notify by email after downloading
enabled: true
trigger:
    type: geoip2.download_unzip
criteria:                              # optional
        trigger: 
          type: "exists" 
          pattern: "path" 
action:
    ref: core.sendmail
    parameters:
        subject: "GeoIP2 was downloaded"
        body: "See at https://st2/GeoLite2.txt \n\n\n{{ trigger.path }}\n\n\n"
        from: "st2@commonwealth.com"
        to: "iromaniuk@commonwealth.com"